# Form implementation generated from reading ui file 'ui_widget.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1241, 771)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(Form)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cam0 = QtWidgets.QLabel(self.verticalFrame)
        self.cam0.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cam0.setObjectName("cam0")
        self.verticalLayout.addWidget(self.cam0)
        self.cam0Screen = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam0Screen.sizePolicy().hasHeightForWidth())
        self.cam0Screen.setSizePolicy(sizePolicy)
        self.cam0Screen.setMinimumSize(QtCore.QSize(600, 400))
        self.cam0Screen.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.cam0Screen.setText("")
        self.cam0Screen.setObjectName("cam0Screen")
        self.verticalLayout.addWidget(self.cam0Screen)
        self.open = QtWidgets.QPushButton(self.verticalFrame)
        self.open.setMinimumSize(QtCore.QSize(0, 30))
        self.open.setObjectName("open")
        self.verticalLayout.addWidget(self.open)
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.verticalFrame_2 = QtWidgets.QFrame(Form)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cam1 = QtWidgets.QLabel(self.verticalFrame_2)
        self.cam1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cam1.setObjectName("cam1")
        self.verticalLayout_2.addWidget(self.cam1)
        self.cam1Screen = QtWidgets.QLabel(self.verticalFrame_2)
        self.cam1Screen.setMinimumSize(QtCore.QSize(600, 400))
        self.cam1Screen.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.cam1Screen.setText("")
        self.cam1Screen.setObjectName("cam1Screen")
        self.verticalLayout_2.addWidget(self.cam1Screen)
        self.param = QtWidgets.QPushButton(self.verticalFrame_2)
        self.param.setMinimumSize(QtCore.QSize(0, 30))
        self.param.setObjectName("param")
        self.verticalLayout_2.addWidget(self.param)
        self.horizontalLayout.addWidget(self.verticalFrame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cam0.setText(_translate("Form", "Cam0"))
        self.open.setText(_translate("Form", "Open"))
        self.cam1.setText(_translate("Form", "Cam1"))
        self.param.setText(_translate("Form", "Params"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
